import GoBack from "@/app/_components/go-back";
import Image from "next/image";

export default function Extremadura() {
  return (
    <main>
      <div className="bg-white flex py-3 items-center sm:py-32 sm:bg-cover sm:bg-[center_52%] sm:bg-[url('/licensed-images/maintenance-engineer-at-solar-farm-looking-drawing-2023-11-27-05-19-47-utc-min.webp')]">
        <h1 className="pl-6 font-semibold mx-auto sm:text-5xl md:text-[var(--green-50-rgb)] text-[var(--green-900-rgb)">
          Extremadura
        </h1>
        <Image
          className="inline sm:hidden"
          src="/graphics-from-the-brandbook/flower-viable-zwart.svg"
          alt="bijen wit"
          width={70}
          height={60}
        />
      </div>
      <div
        className="w-full text-[var(--green-800-rgb)]
                    xl:py-20 xl:px-24 lg:py-16 lg:px-20 md:py-12 md:px-16 sm:py-10 sm:px-12 py-4 px-6"
      >
        <p className="my-2">
          Viable Community is collaborating with local consultants and relevant
          partners to find suitable land to sustainably produce clean energy and
          food while restoring nature. An agrivoltaic project is planned in
          Extremadura to demonstrate sustainable land management practices that
          halt biodiversity loss, combat desertification, and enhance the
          quality of life for the local community.
        </p>
        <p className="my-2">
          We are proud to introduce our Sustainable Land Management project in
          the Extremadura region of Spain.
        </p>
        <p className="my-2">
          In essence, it aims to restore degraded land while simultaneously
          promoting food and energy production.
        </p>
        <p className="my-2">
          Our project seeks to showcase and promote sustainable land management
          practices to halt biodiversity loss, combat desertification, and
          enhance the well-being of the local community.
        </p>

        <h2 className="mt-4">Why do we do it? </h2>
        <p className="my-2">
          The motivation behind our initiative stems from the pressing
          challenges posed by desertification in Extremadura. While the region
          faces the risk of desertification, it still holds potential for
          agriculture. However, if left unchecked, desertification could
          severely impact soil fertility and exacerbate environmental
          degradation.
        </p>
        <p className="my-2">
          Approximately 74% of Spain is at risk of desertification, according to
          Spain&apos;s 2008 National Action Plan (NAP) for the United Nations
          Convention to Combat Desertification (UNCCD), with Extremadura ranking
          among the most vulnerable areas.
        </p>
        <p className="my-2">
          Desertification refers to the degradation of land in arid, semi-arid,
          and dry sub-humid regions, primarily caused by human activities such
          as poor agricultural practices, deforestation, and overgrazing. It is
          crucial to reverse desertification because this process can have
          severe and long-lasting impacts on the environment and human
          communities.
        </p>

        <h2 className="mt-4">What do we do? </h2>
        <p className="my-2">
          This project addresses pressing environmental issues such as
          desertification, biodiversity loss, degradation of soil quality, and
          youth migration through a combination of soil regenerating practices,
          the planting of native vegetation and cover crops, and integrating
          these with AgriVoltaic practices providing shade and sustenance.
        </p>
        <p className="my-2">
          An AgriVoltaic project is a way of producing both food and energy at
          the same time. It involves installing solar panels on the same land
          where crops are grown. This helps to make the most efficient use of
          land, reduces water usage, and can improve the quality and yield of
          crops. The shade provided by the solar panels can also help to create
          a more favorable environment for the crops and help the soil recover.
        </p>
        <p className="my-2">
          Change starts with awareness. Crucially, community engagement lies at
          the heart of our project. We prioritize educating and involving local
          residents in every stage of implementation, empowering them to become
          stewards of their land.Organizing the education of and by the locals
          will provide the necessary knowledge and empower them to initiate
          change themselves.
        </p>
        <p className="my-2">
          The soil will be regenerated by using soil regeneration and
          regenerative agricultural techniques such as introducing mulch with
          beneficial microorganisms like soil microbes and/or fungi to improve
          measurable soil qualities such as microbial diversity and nutrient
          availability. We also collaborate with other volunteer organizations
          to reintroduce native species and implement cover cropping practices,
          enriching the soil and promoting biodiversity.
        </p>
        <p className="my-2">
          We are currently in the process of establishing partnerships and
          consortiums with local organizations and community groups. Through
          these partnerships, we aim to train and employ members of the local
          community and increase plant biodiversity. We believe that our project
          demonstrates the potential for sustainable land use to create positive
          social, environmental, and economic impacts.
        </p>

        <h2 className="mt-4">Impact Areas</h2>
        <p className="my-2">
          Regeneration of 1000 hectares of degraded land, creating meaningful
          employment opportunities for the local population. Integrating 100
          hectares of AgriVoltaics promoting sustainable food and energy
          production.
        </p>
        <p className="my-2">
          Through the integration of agrivoltaic practices and regenerative
          agriculture, our project endeavors to halt desertification, provide
          clean energy access, and promote sustainable livelihoods in one of
          Europe&apos;s most at-risk regions.
        </p>
        <p className="my-2">
          Our initiative not only demonstrates sustainable land management
          practices but also offers tangible benefits to local communities,
          including access to education, clean energy, employment opportunities,
          and nutritious food.
        </p>
        <GoBack />
      </div>
    </main>
  );
}
