export const circles = [
  {
    name: "Strategic",
    description:
      "This circle focuses on overseeing if Viable’s activities are aligned with mission, values, and objectives. We also take care of the day-to-day activities",
  },
  {
    name: "Project development",
    description:
      "The Project development circle at Viable is responsible for planning, designing, implementing, and overseeing projects.",
  },
  {
    name: "Outreach & Communications",
    description:
      "The Outreach and Communications circle is responsible for brand awareness and focusing on fostering a positive public image of Viable’s activities. This circle encompasses the Content Creation circle. The Comms circle is also in charge of monitoring content performance and market analysis, making sure that Viable’s specific goals and objectives are being consistently met.",
  },
  {
    name: "People",
    description:
      "The People Circle at Viable Community is designed to manage volunteers, encourage volunteer engagement and growth, and maintain a progressive work culture.",
  },
  {
    name: "Finance",
    description:
      "Manages Viable's finances, budgeting, and financial reporting",
  },
  {
    name: "IT",
    description:
      "The IT circle at Viable encompasses the Website Development circle and SalesForce circle. They are responsible for managing, maintaining, and leveraging technology to support the organization's operations",
  },
  {
    name: "Daily Operations",
    description:
      "The Operations Circle at Viable Community works with all the circles to ensure the self-managing framework is functional and offers support where needed. This circle also focuses on community engagement and volunteer feedback.",
  },
  {
    name: "Content Creation",
    description:
      "The Content Creation Circle at Viable Community develops and execute marketing campaigns. They also create content ensuring the promotion of Viable’s mission and values.",
  },
];

export const teamMembers = [
  {
    firstName: "Charu",
    lastName: "Patel",
    circle: "People",
    title: "HR Lead",
    imageSrc: "/photos/team-members/Charu.webp",
    linkedinUrl: "https://www.linkedin.com/in/charu-patel/",
  },
  {
    firstName: "Rodney",
    lastName: "Lui",
    circle: "Strategic",
    title: "Strategic Planning Lead",
    imageSrc: "/photos/team-members/Rodney.webp",
    linkedinUrl: "https://www.linkedin.com/in/rodney-lui-aa019724/",
  },
  {
    firstName: "Soumya",
    lastName: "Varma",
    circle: "People",
    title: "People Circle Coordinator",
    imageSrc: "/photos/team-members/Soumya.webp",
    linkedinUrl: "https://www.linkedin.com/in/soumya-varma-57063a1b7",
  },
  {
    firstName: "Vincent",
    lastName: "Adrichem",
    circle: "Daily Operations",
    title: "Executive Director ",
    imageSrc: "/photos/team-members/Vincent.webp",
    linkedinUrl: "https://www.linkedin.com/in/vincent-adrichem",
  },
  {
    firstName: "Abdullah",
    lastName: "Yadgare",
    circle: "Outreach & Communications",
    title: "PR & Communication Coordinator ",
    imageSrc: "/photos/team-members/Abdullah.webp",
    linkedinUrl:
      "https://www.linkedin.com/in/abdullah-yadgare-8a0b73225?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    firstName: "Andrea",
    lastName: "Flores",
    circle: "IT",
    title: "Software Engineer",
    imageSrc: "/photos/team-members/Andrea.webp",
    linkedinUrl: "https://www.linkedin.com/in/andrea-maria-flores/",
  },
  {
    firstName: "Rosemary",
    lastName: "Asufi",
    circle: "Daily Operations",
    title: "Operations Manager",
    imageSrc: "/photos/team-members/Rosemary.webp",
    linkedinUrl: "https://www.linkedin.com/in/rosemary-asufi-6991a853/",
  },
  {
    firstName: "Aibike",
    lastName: "Gaibli",
    circle: "Content Creation",
    title: "Content creator",
    imageSrc: "/photos/team-members/Aibike.webp",
    linkedinUrl: "https://www.linkedin.com/in/aibike-gaibli-a15725248/",
  },
  {
    firstName: "Natalia",
    lastName: "Cornaggia",
    circle: "IT",
    title: "UX/UI",
    imageSrc: "/photos/team-members/Natalia.webp",
    linkedinUrl:
      "https://www.linkedin.com/in/nataliacornaggia/?originalSubdomain=nl",
  },
  {
    firstName: "Angel",
    lastName: "Garcia",
    circle: "Project development",
    title: "Country Manager Spain",
    imageSrc: "/photos/team-members/Angel.webp",
    linkedinUrl: "https://www.linkedin.com/in/angel-david-garcia-barrio/",
  },
  {
    firstName: "Michael",
    lastName: "Ukwuma",
    circle: "Content Creation",
    title: "Content creator",
    imageSrc: "/photos/team-members/Michael.webp",
    linkedinUrl: "https://www.linkedin.com/in/michaelukwuma/",
  },
  {
    firstName: "Damarice",
    lastName: "Akinyi",
    circle: "IT",
    title: "Web3 Developer",
    imageSrc: "/photos/team-members/Damarice.webp",
    linkedinUrl: "https://www.linkedin.com/in/damarice-akinyi-b2187799/",
  },
  {
    firstName: "Tymon",
    lastName: "Glos",
    circle: "IT",
    title: "Web3 Developer",
    imageSrc: "/photos/team-members/Tymon.webp",
    linkedinUrl: "https://www.linkedin.com/in/tymon-glos-a595682ab/",
  },
  {
    firstName: "Scarlett",
    lastName: "Jary",
    circle: "Daily Operations",
    title: "Operations Manager",
    imageSrc: "/photos/team-members/Scarlet.webp",
    linkedinUrl: "https://www.linkedin.com/in/scarlett-jary-1b47b91a2/",
  },
  {
    firstName: "Sahar",
    lastName: "Koolaee",
    circle: "IT",
    title: "UX designer",
    imageSrc: "/photos/team-members/Sahar.webp",
    linkedinUrl: "https://www.linkedin.com/in/sahar-koolaee-30230b205/",
  },
  {
    firstName: "Mercy",
    lastName: "Ogalo",
    circle: "IT",
    title: "Front-end developer",
    imageSrc: "/photos/team-members/Mercy.webp",
    linkedinUrl: "https://www.linkedin.com/in/mercy-ogalo-9a1b69272/",
  },
  {
    firstName: "Kate",
    lastName: "McGuinness",
    circle: "People",
    title: "HR coordinator",
    imageSrc: "/photos/team-members/Kate.webp",
    linkedinUrl: "https://www.linkedin.com/company/viable-community",
  },
  {
    firstName: "Jingwen",
    lastName: "Zheng",
    circle: "IT",
    title: "Frontend developer",
    imageSrc: "/photos/team-members/Jingwen.webp",
    linkedinUrl: "https://www.linkedin.com/in/jw-zheng/",
  },
  {
    firstName: "Zhen",
    lastName: "",
    circle: "Outreach & Communications",
    title: "Content creator",
    imageSrc: "/photos/team-members/Zhen.webp",
    linkedinUrl: "https://www.linkedin.com/company/viable-community",
  },
  {
    firstName: "Matin",
    lastName: "Mozaffari",
    circle: "Project development",
    title: "Project development Researcher",
    imageSrc: "/photos/team-members/Matin.webp",
    linkedinUrl:
      "https://www.linkedin.com/in/matin-khadem-mozaffari-846733317/",
  },
  {
    firstName: "Oladunni",
    lastName: "Olabisi",
    circle: "Project development",
    title: "Project development Assistant",
    imageSrc: "/photos/team-members/placeholder.webp",
    linkedinUrl: "https://www.linkedin.com/in/oladunni-olabisi",
  },
  {
    firstName: "Abdulraheem",
    lastName: "Alkasadi",
    circle: "Finance",
    title: "Finance consultant",
    imageSrc: "/photos/team-members/Abdulraheem.webp",
    linkedinUrl: "https://www.linkedin.com/company/viable-community",
  },
  {
    firstName: "Eunike",
    lastName: "Pardede",
    circle: "IT",
    title: "Front-end Developer",
    imageSrc: "/photos/team-members/Eunike.webp",
    linkedinUrl: "https://www.linkedin.com/in/eunikepardede/",
  },
  {
    firstName: "Maria Victoria",
    lastName: "Cincurá",
    circle: "Strategic",
    title: "Strategic Consultant",
    imageSrc: "/photos/team-members/MariaVitoria.webp",
    linkedinUrl: "https://www.linkedin.com/in/maria-victoria-folkerts-cincura/",
  },
  {
    firstName: "Annette",
    lastName: "Thia",
    circle: "People",
    title: "Volunteer",
    imageSrc: "/photos/team-members/Annette.webp",
    linkedinUrl: "https://www.linkedin.com/in/annettethia/",
  },
  {
    firstName: "Thuraya",
    lastName: "Al-Jebori",
    circle: "Daily Operations",
    title: "Program Manager",
    imageSrc: "/photos/team-members/Thuraya.webp",
    linkedinUrl: "https://www.linkedin.com/in/thurayaal-jebori/",
  },
  {
    firstName: "Varsha",
    lastName: "Goyal",
    circle: "Outreach & Communications",
    title: "Impact and Sustainability Advocate",
    imageSrc: "/photos/team-members/Varsha.webp",
    linkedinUrl: "https://www.linkedin.com/in/varshagoyal/",
  },
  {
    firstName: "Bernice",
    lastName: "Asaah",
    circle: "IT",
    title: "Web Developer",
    imageSrc: "/photos/team-members/Bernice.webp",
    linkedinUrl: "https://www.linkedin.com/in/bernice-asaah-5326b0225/",
  },
  {
    firstName: "Tecia",
    lastName: "Vailati",
    circle: "IT",
    title: "Front-end Developer",
    imageSrc: "/photos/team-members/Tecia.webp",
    linkedinUrl: "https://www.linkedin.com/in/teciavailati/",
  },
  {
    firstName: "Shelly",
    lastName: "Tsui",
    circle: "Content Creation",
    title: "Content Creation Coordinator",
    imageSrc: "/photos/team-members/Shelly.webp",
    linkedinUrl: "https://www.linkedin.com/in/shelly-tsui-9302/",
  },
  {
    firstName: "Pablo",
    lastName: "Rios",
    circle: "IT",
    title: "Product Owner",
    imageSrc: "/photos/team-members/Pablo.webp",
    linkedinUrl: "https://www.linkedin.com/in/pablorios/",
  },
  {
    firstName: "Akanksha",
    lastName: "Singh",
    circle: "IT",
    title: "Product Owner",
    imageSrc: "/photos/team-members/Akanksha.webp",
    linkedinUrl: "https://www.linkedin.com/in/akanksha-singh-5396567/",
  },
  {
    firstName: "Léa",
    lastName: "Allix-Cornelissen",
    circle: "People",
    title: "Volunteer",
    imageSrc: "/photos/team-members/placeholder.webp",
    linkedinUrl: "https://www.linkedin.com/company/viable-community",
  },
  {
    firstName: "Khushboo",
    lastName: "Shrivastava",
    circle: "IT",
    title: "Web Developer",
    imageSrc: "/photos/team-members/Khushboo.webp",
    linkedinUrl: "https://www.linkedin.com/company/viable-community",
  },
  {
    firstName: "Joshua",
    lastName: "Nuku",
    circle: "IT",
    title: "Software Developer",
    imageSrc: "/photos/team-members/Joshua.webp",
    linkedinUrl: "https://www.linkedin.com/in/josh-nuku-7aa67422b/",
  },
  {
    firstName: "Huien",
    lastName: "Tan",
    circle: "IT",
    title: "Senior Front-end Developer",
    imageSrc: "/photos/team-members/Huien.webp",
    linkedinUrl: "https://nl.linkedin.com/in/huien-tan",
  },
  {
    firstName: "Afekhide",
    lastName: "Gbadamosi",
    circle: "IT",
    title: "Web Development Team Coordinator",
    imageSrc: "/photos/team-members/Afe.webp",
    linkedinUrl: "https://www.linkedin.com/in/afekhide-gbadamosi-171005104",
  },
  {
    firstName: "Sindhuja",
    lastName: "Narayanamurthy",
    circle: "IT",
    title: "Salesforce Implementation Specialist",
    imageSrc: "/photos/team-members/Sindhuja.webp",
    linkedinUrl: "https://www.linkedin.com/company/viable-community",
  },
];
